<a href="https://colab.research.google.com/github/jakubglinka/google.colab/blob/master/NLP/supervised/BertSequenceClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text Classification using BERT

 - training smaller Transformer from scratch
 - using pre-trained bert model
 - distil knowledge to smaller transformer

## Configure environment

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
print(tf.__version__)

TensorFlow 2.x selected.
Num GPUs Available:  0
2.1.0-rc1


In [0]:
try:
  cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
  tf.config.experimental_connect_to_cluster(cluster_resolver)
  tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
  strategy = tf.distribute.experimental.TPUStrategy(cluster_resolver)
except ValueError as error:
  print(error)
  print("No TPU available. Switching to single device strategy.")
  strategy = tf.distribute.OneDeviceStrategy(device="/gpu")

INFO:tensorflow:Initializing the TPU system: 10.51.20.234:8470


INFO:tensorflow:Initializing the TPU system: 10.51.20.234:8470


INFO:tensorflow:Clearing out eager caches


INFO:tensorflow:Clearing out eager caches


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Found TPU system:


INFO:tensorflow:Found TPU system:


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


In [0]:
!pip install transformers
!pip install git+https://jbglin:botrx56jtlp6p2cbsthvt3bkslgeo3pzc5c7iuu4irxscjmmc6xa@dev.azure.com/eyDataScienceTeam/_git/nlp-ey-assets@develop

## Data Preparation

### PolEmo data

In [0]:
import pandas as pd
import pathlib
import re
import tqdm
POLEMO_PATH = "./drive/My Drive/sentiment/"
from typing import List
import numpy as np

In [0]:
# read PolEmo data:
def read_polemo_data(path) -> pd.DataFrame:
  res = []
  with path.open("r") as f:
    for line in f:
      rec = line.strip("\n").split("__label__")
      rec[0] = rec[0].strip()
      res.append(rec)

  return pd.DataFrame(res, columns=["text", "label"])

df_train = read_polemo_data(pathlib.Path(POLEMO_PATH) / "all.sentence.train.txt")
print(f"Read {df_train.shape[0]} train examples.")

df_dev = read_polemo_data(pathlib.Path(POLEMO_PATH) / "all.sentence.dev.txt")
print(f"Read {df_dev.shape[0]} dev examples.")

df_test = read_polemo_data(pathlib.Path(POLEMO_PATH) / "all.sentence.test.txt")
print(f"Read {df_test.shape[0]} test examples.")

Read 45974 train examples.
Read 5747 dev examples.
Read 5745 test examples.


In [0]:
df_train.iloc[5745, :]

text     Niestety mam podobne odczucia jak poprzedniczka .
label                                            z_minus_m
Name: 5745, dtype: object

In [0]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder().fit(df_train.label.values)

# add encoded labels:
df_train["label_enc"] = enc.transform(df_train["label"])
df_dev["label_enc"] = enc.transform(df_dev["label"])
df_test["label_enc"] = enc.transform(df_test["label"])

## Small Transformer

### Architecture

![alt text](https://miro.medium.com/max/3740/1*hC4zIxPPK9KGDu-OYUfnCQ.png)

### Settings

*   vocab_size: 4000
*   hidden_size: 256
*   num_hidden_layers: 4
*   num_attention_heads: 4
*   intermediate_size: 1024
*   max_position_embeddings: 128

### Prepare `BertTokenizer`

In [0]:
from nlp.tokenizers import SentencePieceTokenizer
from transformers import BertTokenizer
from absl import logging
logging.set_verbosity(logging.INFO)

SP_TO_LOWER = False
SP_MAX_VOCAB_SIZE = 10000

In [0]:
# initialize tokenizer:
tokenizer = SentencePieceTokenizer(lower=SP_TO_LOWER, strip_accents=SP_TO_LOWER)

# prepare segments:
segments = list(df_train.text) + list(df_dev.text) + list(df_test.text)

# fit tokenizer:
tokenizer.fit_on_segments(segments=segments, max_vocab_size=SP_MAX_VOCAB_SIZE)

100%|██████████████████████████████████████████████████████████████████████████| 57466/57466 [00:05<00:00, 11486.44it/s]


In [0]:
# save vocabulary to disk in the format compatible with BertTokenizer:
BERT_SPECIAL_TOKENS = ["[PAD]", "[UNK]", "[SEP]", "[CLS]", "[MASK]"]
vocab = tokenizer.get_vocabulary()

with pathlib.Path("./sentencepiece.vocab").open("w") as f:
  for token in BERT_SPECIAL_TOKENS:
    f.write(token + "\n")
  for idx, (word, __) in enumerate(vocab.items()):
    if idx > 3:
      if word.startswith("▁"):
        word = word.replace("▁", "")
      else:
        word = "##" + word
      f.write(word + "\n")

!head -n 7 ./sentencepiece.vocab

[PAD]
[UNK]
[SEP]
[CLS]
[MASK]
.
,


In [0]:
# create new instance of BertTokenizer
bert_tokenizer = BertTokenizer("./sentencepiece.vocab", do_lower_case=SP_TO_LOWER, do_basic_tokenize=True)
print(bert_tokenizer.tokenize("Ala ma kota!"))

# encode plus:
bert_tokenizer.encode_plus("Ala ma kota!", max_length=10, pad_to_max_length=True)

['Al', '##a', 'ma', 'kot', '##a', '!']


{'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
 'input_ids': [3, 4126, 7, 66, 2121, 7, 40, 2, 0, 0],
 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

In [0]:
# check for number of tokens distribution
df_train["n_tokens"] = df_train.text.apply(lambda x: len(bert_tokenizer.tokenize(x)))
np.quantile(df_train.n_tokens, q=[.9, .99, .999])

array([ 50.   , 103.   , 193.108])

In [0]:
# from transformers import BertTokenizer

# vocab = ["byli", "##śmy", "Byli", "##smy", "."]
# with open("/tmp/test.vocab", "w") as f:
#   for wordpiece in vocab:
#     f.write(wordpiece + "\n")

# bert_tokenizer = BertTokenizer("/tmp/test.vocab", do_basic_tokenize=True, do_lower_case=True)
# bert_tokenizer.tokenize("Byliśmy.")

### TFRecords

#### Prepare single Example

In [0]:
bert_tokenizer.tokenize("za późno, polecam")

['za', 'późno', ',', 'polecam']

In [0]:
from typing import Dict
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# prepare data:
def _prepare_single_example(x: str, max_seq_len: int = None, label: int = 0) -> Dict:
  
  inputs = bert_tokenizer.encode_plus(x, max_length=max_seq_len, pad_to_max_length=False, return_tensors="tf")
  inputs["attention_mask"] = tf.squeeze(inputs["attention_mask"], axis=0)
  inputs["input_ids"] = tf.squeeze(inputs["input_ids"], axis=0)
  inputs["token_type_ids"] = tf.squeeze(inputs["token_type_ids"], axis=0)
  
  inputs["label"] = tf.convert_to_tensor(label)
  inputs["raw_text"] = tf.convert_to_tensor(x)

  return inputs

# serialize:
def _serialize_example(example):
  
  # attention mask
  example["attention_mask"] = tf.io.serialize_tensor(example["attention_mask"]).numpy()
  example["attention_mask"] = tf.train.Feature(bytes_list = tf.train.BytesList(value=[example["attention_mask"]]))
  
  # input ids
  example["input_ids"] = tf.io.serialize_tensor(example["input_ids"]).numpy()
  example["input_ids"] = tf.train.Feature(bytes_list = tf.train.BytesList(value=[example["input_ids"]]))

  # token type ids
  example["token_type_ids"] = tf.io.serialize_tensor(example["token_type_ids"]).numpy()
  example["token_type_ids"] = tf.train.Feature(bytes_list = tf.train.BytesList(value=[example["token_type_ids"]]))

  example["raw_text"] = tf.train.Feature(bytes_list = tf.train.BytesList(value=[example["raw_text"].numpy()]))
  example["label"] = tf.train.Feature(int64_list = tf.train.Int64List(value=[example["label"].numpy()]))

  ex = tf.train.Example(features=tf.train.Features(feature=example))
  return ex.SerializeToString()  

# example = _prepare_single_example("Ala ma kota!", 64, 1)
# example
# tf.train.Example.FromString(_serialize_example(example))

#### Prepare TFRecords

In [0]:
!rm ./train.TFRecord ./dev.TFRecord ./test.TFRecord

In [0]:
# Write the `tf.Example` observations to the file.

with tf.io.TFRecordWriter("./train.TFRecord") as writer:
  for __, row in tqdm.tqdm(df_train.iterrows()):
    example = _prepare_single_example(row.text, None, row.label_enc)
    writer.write(_serialize_example(example))

with tf.io.TFRecordWriter("./dev.TFRecord") as writer:
  for __, row in tqdm.tqdm(df_dev.iterrows()):
    example = _prepare_single_example(row.text, None, row.label_enc)
    writer.write(_serialize_example(example))

with tf.io.TFRecordWriter("./test.TFRecord") as writer:
  for __, row in tqdm.tqdm(df_test.iterrows()):
    example = _prepare_single_example(row.text, None, row.label_enc)
    writer.write(_serialize_example(example))


45974it [05:52, 130.60it/s]
5747it [00:43, 131.11it/s]
5745it [00:46, 124.16it/s]


In [0]:
!ls -la -h | grep TF

-rw-r--r-- 1 root root 3.4M Jan  4 12:59 dev.TFRecord
-rw-r--r-- 1 root root 3.4M Jan  4 13:00 test.TFRecord
-rw-r--r-- 1 root root  27M Jan  4 12:58 train.TFRecord


#### Copy to GC Bucket

In [0]:
from google.colab import auth
auth.authenticate_user()

# https://cloud.google.com/resource-manager/docs/creating-managing-projects
project_id = 'southern-shard-211411'
!gcloud config set project {project_id}

Updated property [core/project].


In [0]:
# Upload the files to a given Google Cloud Storage bucket.
!gsutil cp ./train.TFRecord gs://tf_experiments_records/PolEmo/train.TFRecord
!gsutil cp ./dev.TFRecord gs://tf_experiments_records/PolEmo/dev.TFRecord
!gsutil cp ./test.TFRecord gs://tf_experiments_records/PolEmo/test.TFRecord

Copying file://./train.TFRecord [Content-Type=application/octet-stream]...
-
Operation completed over 1 objects/26.6 MiB.                                     
Copying file://./dev.TFRecord [Content-Type=application/octet-stream]...
/ [1 files][  3.4 MiB/  3.4 MiB]                                                
Operation completed over 1 objects/3.4 MiB.                                      
Copying file://./test.TFRecord [Content-Type=application/octet-stream]...
-
Operation completed over 1 objects/3.3 MiB.                                      


### Read from GC Bucket

In [0]:
from google.colab import auth
auth.authenticate_user()

# https://cloud.google.com/resource-manager/docs/creating-managing-projects
project_id = 'southern-shard-211411'
!gcloud config set project {project_id}

Updated property [core/project].


In [0]:
# Set access for the TPU pod:
!gsutil acl ch -u service-495559152420@cloud-tpu.iam.gserviceaccount.com:READER gs://tf_experiments_records/PolEmo/train.TFRecord
!gsutil acl ch -u service-495559152420@cloud-tpu.iam.gserviceaccount.com:READER gs://tf_experiments_records/PolEmo/dev.TFRecord
!gsutil acl ch -u service-495559152420@cloud-tpu.iam.gserviceaccount.com:READER gs://tf_experiments_records/PolEmo/test.TFRecord

Updated ACL on gs://tf_experiments_records/PolEmo/train.TFRecord
Updated ACL on gs://tf_experiments_records/PolEmo/dev.TFRecord
Updated ACL on gs://tf_experiments_records/PolEmo/test.TFRecord


In [0]:
# Create a dictionary describing the features.
_feature_description = {
    'attention_mask': tf.io.FixedLenFeature([], tf.string),
    'input_ids': tf.io.FixedLenFeature([], tf.string),
    'token_type_ids': tf.io.FixedLenFeature([], tf.string),
    'label': tf.io.FixedLenFeature([], tf.int64)
}

def _parse_data(example_proto, max_seq_len: int = 128):
  # Parse the input tf.Example proto using the dictionary above.
  rec = tf.io.parse_single_example(example_proto, _feature_description)
  
  # attention_mask:
  rec["attention_mask"] = tf.io.parse_tensor(rec["attention_mask"], out_type=tf.int32)
  rec["attention_mask"] = rec["attention_mask"][:max_seq_len]
  n_tokens = tf.shape(rec["attention_mask"])[0]
  padding = max_seq_len - n_tokens
  rec["attention_mask"] = tf.pad(rec["attention_mask"], paddings=[[0, padding]])

  # input_ids:
  rec["input_ids"] = tf.io.parse_tensor(rec["input_ids"], out_type=tf.int32)
  rec["input_ids"] = rec["input_ids"][:max_seq_len]
  rec["input_ids"] = tf.pad(rec["input_ids"], paddings=[[0, padding]])
  
  # token_type_ids
  rec["token_type_ids"] = tf.io.parse_tensor(rec["token_type_ids"], out_type=tf.int32)
  rec["token_type_ids"] = rec["token_type_ids"][:max_seq_len]
  rec["token_type_ids"] = tf.pad(rec["token_type_ids"], paddings=[[0, padding]])
 
  # shape bug?
  # rec["text/embedding"] = tf.reshape(rec["text/embedding"], [64, 256])
  rec["attention_mask"] = tf.reshape(rec["attention_mask"], [max_seq_len, ])
  rec["input_ids"] = tf.reshape(rec["input_ids"], [max_seq_len, ])
  rec["token_type_ids"] = tf.reshape(rec["token_type_ids"], [max_seq_len, ])
 
  labels = tf.one_hot(rec["label"], depth=4)
  inputs = rec
  inputs.pop("label")

  return inputs, labels

train_raw = tf.data.TFRecordDataset("gs://tf_experiments_records/PolEmo/train.TFRecord", num_parallel_reads=4)
example_proto = next(iter(train_raw))
_parse_data(example_proto, max_seq_len=12)

({'attention_mask': <tf.Tensor: shape=(12,), dtype=int32, numpy=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)>,
  'input_ids': <tf.Tensor: shape=(12,), dtype=int32, numpy=
  array([  101, 38217, 11669, 57482, 14052, 10381, 42863, 10637, 10132,
         37598,   117, 59685], dtype=int32)>,
  'token_type_ids': <tf.Tensor: shape=(12,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>},
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 1.], dtype=float32)>)

In [0]:
BATCH_SIZE = 8*64
STEPS_PER_EPOCH = int(np.floor(45000 / BATCH_SIZE))
VALIDATION_STEPS = int(np.floor(5700 / BATCH_SIZE))

print(f"STEPS_PER_EPOCH: {STEPS_PER_EPOCH}")
print(f"VALIDATION_STEPS: {VALIDATION_STEPS}")

train_raw = tf.data.TFRecordDataset("gs://tf_experiments_records/PolEmo/train.TFRecord", num_parallel_reads=1)
train_parsed = train_raw.map(_parse_data).batch(BATCH_SIZE, drop_remainder=True).repeat(100)
train_parsed = train_parsed.prefetch(-1)

inputs, labels = next(iter(train_parsed))

dev_raw = tf.data.TFRecordDataset("gs://tf_experiments_records/PolEmo/dev.TFRecord", num_parallel_reads=1)
dev_parsed = dev_raw.map(_parse_data).batch(BATCH_SIZE, drop_remainder=True)
dev_parsed = dev_parsed.prefetch(-1)

test_raw = tf.data.TFRecordDataset("gs://tf_experiments_records/PolEmo/test.TFRecord", num_parallel_reads=1)
test_parsed = test_raw.map(_parse_data).batch(BATCH_SIZE, drop_remainder=True)
test_parsed = test_parsed.prefetch(-1)

inputs

STEPS_PER_EPOCH: 87
VALIDATION_STEPS: 11


{'attention_mask': <tf.Tensor: shape=(512, 128), dtype=int32, numpy=
 array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>,
 'input_ids': <tf.Tensor: shape=(512, 128), dtype=int32, numpy=
 array([[   3,  593,   74, ...,    0,    0,    0],
        [   3,  165,  169, ...,    0,    0,    0],
        [   3,   52,    9, ...,    0,    0,    0],
        ...,
        [   3, 3727,   18, ...,    0,    0,    0],
        [   3,   96,  202, ...,    0,    0,    0],
        [   3,  128,   11, ...,    0,    0,    0]], dtype=int32)>,
 'token_type_ids': <tf.Tensor: shape=(512, 128), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>}

### `BertConfig`

In [0]:
from transformers import BertConfig
from transformers import TFBertForSequenceClassification

# new config
config = BertConfig(vocab_size=10000, output_hidden_states=False,
                    hidden_size=128, 
                    num_attention_heads=4, 
                    num_hidden_layers=4, 
                    intermediate_size=256, 
                    max_position_embeddings=128,
                    num_labels=4, 
                    hidden_dropout_prob=0.1, 
                    attention_probs_dropout_prob=0.1)

### Model training

In [0]:
with strategy.scope():
  tf.random.set_seed(1234)
  model = TFBertForSequenceClassification(config)

  initial_learning_rate = 1e-3
  lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate,
    decay_steps=STEPS_PER_EPOCH,
    decay_rate=.9,
    staircase=True)
  
  model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr_schedule), 
                loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True), 
                metrics=[tf.keras.metrics.CategoricalAccuracy()])

In [0]:
callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=1)
model.fit(train_parsed, 
          validation_data=dev_parsed, 
          epochs=100, 
          steps_per_epoch=STEPS_PER_EPOCH, 
          validation_steps=VALIDATION_STEPS,
          callbacks=[callback])

Train for 87 steps, validate for 11 steps
Epoch 1/100
87/87 [==============================] - 27s 308ms/step - loss: 1.1414 - categorical_accuracy: 0.5081 - val_loss: 0.8950 - val_categorical_accuracy: 0.6644
Epoch 2/100
87/87 [==============================] - 4s 41ms/step - loss: 0.7831 - categorical_accuracy: 0.7069 - val_loss: 0.8502 - val_categorical_accuracy: 0.6880
Epoch 3/100
87/87 [==============================] - 3s 40ms/step - loss: 0.6361 - categorical_accuracy: 0.7682 - val_loss: 0.8810 - val_categorical_accuracy: 0.6863


In [0]:
model.summary()
!nvidia-smi

Model: "tf_bert_for_sequence_classification_22"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bert (TFBertMainLayer)       multiple                  1843328   
_________________________________________________________________
dropout_369 (Dropout)        multiple                  0         
_________________________________________________________________
classifier (Dense)           multiple                  516       
Total params: 1,843,844
Trainable params: 1,843,844
Non-trainable params: 0
_________________________________________________________________
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



### Model accuracy

In [0]:
from sklearn.metrics import classification_report
import numpy as np

# y_pred
y_pred = model.predict(test_parsed)
y_pred = np.argmax(y_pred, axis=1)
y_pred

# y_true
y_true = []  
for __, labels in test_parsed:
  y_true += list(np.argmax(labels.numpy(), axis=1))

In [0]:
print(classification_report(y_true=y_true, y_pred=y_pred, digits=3))

              precision    recall  f1-score   support

           0      0.593     0.301     0.399       668
           1      0.701     0.754     0.727      2087
           2      0.730     0.703     0.716      1489
           3      0.645     0.751     0.694      1388

    accuracy                          0.686      5632
   macro avg      0.667     0.627     0.634      5632
weighted avg      0.682     0.686     0.677      5632



### Error analysis

In [0]:
# one-hot encode label:
def _one_hot(i: int, num_classes: int = 4):
  res = np.zeros(num_classes)
  res[i] = 1.0
  return res

df_dev["y_true"] = df_dev.label_enc.apply(lambda i: _one_hot(i, 4)) 

# add prediction from the model
def _predict(text: str):
  inputs = bert_tokenizer.encode_plus(text, return_tensors="tf")
  probs = tf.math.softmax(model(inputs)[0]).numpy()[0, :]
  return probs

preds = []
for text in tqdm.tqdm(df_dev.text):
  preds.append(_predict(text))

df_dev["y_pred"] = preds

In [0]:
def _error_rate(row):
  if row.y_true[1]>0.0:
    return 1-row.y_pred[1]
  elif row.y_true[2]>0.0:
    return 1-row.y_pred[2]
  else:
    return 0.0

df_dev["err"] = df_dev.apply(_error_rate, axis=1)
df_dev = df_dev.sort_values("err", ascending=False)
df_dev.head(10)

text  ...       err
1874                                 Uwazni ratownicy .  ...  0.997241
5066  Byli śmy w motelu 2 tygodnie i poznali śmy tam...  ...  0.997008
333   W samym Lądku znam kilka lepszych lokalizacji ...  ...  0.996806
3285       Terenu jest od groma , żeby to wykorzystać .  ...  0.996636
4840  Operacja trwała prawie dwie godziny , dokładni...  ...  0.996539
3412  Na plazy sporo turystów - więc gmina powinna z...  ...  0.996024
1785  Jednak jestem teraz nowym , wolnym i lepszym c...  ...  0.995976
5218  Kiedyś była z rozwojem motorycznym za równieśn...  ...  0.995953
2700  Kwestia meldunku w moim przypadku to około 2 m...  ...  0.995659
4670  Obyśmy dożyli takich lekarzy w państwowej Służ...  ...  0.995572

[10 rows x 6 columns]

In [0]:
# prediction examples with the biggest error:
text = df_dev.loc[4670, "text"]

def _predict(text: str):
  inputs = bert_tokenizer.encode_plus(text, return_tensors="tf")
  probs = tf.math.softmax(model(inputs)[0]).numpy()[0, :]
  return probs

probs = _predict(text)
probs
idx = np.argmax(probs)
idx

print(f"{bert_tokenizer.tokenize(text)}: {enc.classes_[idx]}, p={probs[idx]}")

['Ob', '##y', '##ś', '##my', 'do', '##ż', '##y', '##li', 'taki', '##ch', 'lekarz', '##y', 'w', 'państwow', '##ej', 'S', '##ł', '##u', '##ż', '##bie', 'Zdrowi', '##a', '.', '.', '.', '.']: z_zero, p=0.9859784245491028


## Pre-Trained BERT
 - bert-base-multilingual-cased

### Prepare BertTokenizer

In [0]:
from transformers import BertTokenizer, TFBertForSequenceClassification

In [0]:
# create new instance of BertTokenizer
bert_tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
print(bert_tokenizer.tokenize("Ala ma kota!"))

# encode plus:
bert_tokenizer.encode_plus("Ala ma kota!", max_length=10, pad_to_max_length=True)

['Ala', 'ma', 'kota', '!']


{'attention_mask': [1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
 'input_ids': [101, 56500, 10824, 16469, 106, 102, 0, 0, 0, 0],
 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

In [0]:
# check for number of tokens distribution
df_train["n_tokens"] = df_train.text.apply(lambda x: len(bert_tokenizer.tokenize(x)))
np.quantile(df_train.n_tokens, q=[.9, .99, .999])

array([ 59.   , 122.   , 243.027])

### TFRecords

In [0]:
!rm ./train.TFRecord ./dev.TFRecord ./test.TFRecord

In [0]:
# Write the `tf.Example` observations to the file.

with tf.io.TFRecordWriter("./train.TFRecord") as writer:
  for __, row in tqdm.tqdm(df_train.iterrows()):
    example = _prepare_single_example(row.text, None, row.label_enc)
    writer.write(_serialize_example(example))

with tf.io.TFRecordWriter("./dev.TFRecord") as writer:
  for __, row in tqdm.tqdm(df_dev.iterrows()):
    example = _prepare_single_example(row.text, None, row.label_enc)
    writer.write(_serialize_example(example))

with tf.io.TFRecordWriter("./test.TFRecord") as writer:
  for __, row in tqdm.tqdm(df_test.iterrows()):
    example = _prepare_single_example(row.text, None, row.label_enc)
    writer.write(_serialize_example(example))


45974it [05:36, 136.46it/s]
5747it [00:42, 135.57it/s]
5745it [00:43, 133.05it/s]


In [0]:
!ls -la -h | grep TF

-rw-r--r-- 1 root root 3.8M Jan  4 15:37 dev.TFRecord
-rw-r--r-- 1 root root 3.8M Jan  4 15:38 test.TFRecord
-rw-r--r-- 1 root root  30M Jan  4 15:36 train.TFRecord


### Copy to GC Bucket

In [0]:
from google.colab import auth
auth.authenticate_user()

# https://cloud.google.com/resource-manager/docs/creating-managing-projects
project_id = 'southern-shard-211411'
!gcloud config set project {project_id}

Updated property [core/project].


In [0]:
# Upload the files to a given Google Cloud Storage bucket.
!gsutil cp ./train.TFRecord gs://tf_experiments_records/PolEmo/train.TFRecord
!gsutil cp ./dev.TFRecord gs://tf_experiments_records/PolEmo/dev.TFRecord
!gsutil cp ./test.TFRecord gs://tf_experiments_records/PolEmo/test.TFRecord

Copying file://./train.TFRecord [Content-Type=application/octet-stream]...
-
Operation completed over 1 objects/29.6 MiB.                                     
Copying file://./dev.TFRecord [Content-Type=application/octet-stream]...
/ [1 files][  3.8 MiB/  3.8 MiB]                                                
Operation completed over 1 objects/3.8 MiB.                                      
Copying file://./test.TFRecord [Content-Type=application/octet-stream]...
/ [1 files][  3.7 MiB/  3.7 MiB]                                                
Operation completed over 1 objects/3.7 MiB.                                      


### Read from GC Bucket

In [0]:
# Set access for the TPU pod:
!gsutil acl ch -u service-495559152420@cloud-tpu.iam.gserviceaccount.com:READER gs://tf_experiments_records/PolEmo/train.TFRecord
!gsutil acl ch -u service-495559152420@cloud-tpu.iam.gserviceaccount.com:READER gs://tf_experiments_records/PolEmo/dev.TFRecord
!gsutil acl ch -u service-495559152420@cloud-tpu.iam.gserviceaccount.com:READER gs://tf_experiments_records/PolEmo/test.TFRecord

No changes to gs://tf_experiments_records/PolEmo/train.TFRecord
No changes to gs://tf_experiments_records/PolEmo/dev.TFRecord
No changes to gs://tf_experiments_records/PolEmo/test.TFRecord


In [0]:
BATCH_SIZE = 8*32
STEPS_PER_EPOCH = int(np.floor(45000 / BATCH_SIZE))
VALIDATION_STEPS = int(np.floor(5700 / BATCH_SIZE))

print(f"STEPS_PER_EPOCH: {STEPS_PER_EPOCH}")
print(f"VALIDATION_STEPS: {VALIDATION_STEPS}")

train_raw = tf.data.TFRecordDataset("gs://tf_experiments_records/PolEmo/train.TFRecord", num_parallel_reads=1)
train_parsed = train_raw.map(_parse_data).batch(BATCH_SIZE, drop_remainder=True).repeat(100)
train_parsed = train_parsed.prefetch(-1)

inputs, labels = next(iter(train_parsed))

dev_raw = tf.data.TFRecordDataset("gs://tf_experiments_records/PolEmo/dev.TFRecord", num_parallel_reads=1)
dev_parsed = dev_raw.map(_parse_data).batch(BATCH_SIZE, drop_remainder=True)
dev_parsed = dev_parsed.prefetch(-1)

test_raw = tf.data.TFRecordDataset("gs://tf_experiments_records/PolEmo/test.TFRecord", num_parallel_reads=1)
test_parsed = test_raw.map(_parse_data).batch(BATCH_SIZE, drop_remainder=True)
test_parsed = test_parsed.prefetch(-1)

inputs

STEPS_PER_EPOCH: 175
VALIDATION_STEPS: 22


{'attention_mask': <tf.Tensor: shape=(256, 128), dtype=int32, numpy=
 array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>,
 'input_ids': <tf.Tensor: shape=(256, 128), dtype=int32, numpy=
 array([[  101, 38217, 11669, ...,     0,     0,     0],
        [  101, 11791, 15905, ...,     0,     0,     0],
        [  101,   160, 20728, ...,     0,     0,     0],
        ...,
        [  101, 11255, 56359, ...,     0,     0,     0],
        [  101, 11255, 24378, ...,     0,     0,     0],
        [  101, 32224, 10451, ...,     0,     0,     0]], dtype=int32)>,
 'token_type_ids': <tf.Tensor: shape=(256, 128), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ...,

### Model training

In [0]:
with strategy.scope():
  tf.random.set_seed(1234)
  model = TFBertForSequenceClassification.from_pretrained('bert-base-multilingual-cased', 
                                                          num_labels=4, 
                                                          hidden_dropout_prob=0.1, 
                                                          attention_probs_dropout_prob=0.1)

  initial_learning_rate = 1e-5
  lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate,
    decay_steps=STEPS_PER_EPOCH*10000,
    decay_rate=.99,
    staircase=True)
  
  model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr_schedule), 
                loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True), 
                metrics=[tf.keras.metrics.CategoricalAccuracy()])

In [0]:
callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=5)
checkpoint = tf.keras.callbacks.ModelCheckpoint(filepath="/tmp/weights.{epoch:02d}-{val_loss:.2f}.hdf5", monitor="val_loss", save_best_only=True)
model.fit(train_parsed, 
          validation_data=dev_parsed, 
          epochs=100,
          steps_per_epoch=STEPS_PER_EPOCH, 
          validation_steps=VALIDATION_STEPS,
          callbacks=[callback, checkpoint])

Train for 175 steps, validate for 22 steps
Epoch 1/100
175/175 [==============================] - 122s 700ms/step - loss: 1.0060 - categorical_accuracy: 0.5900 - val_loss: 0.8127 - val_categorical_accuracy: 0.6848
Epoch 2/100
175/175 [==============================] - 51s 294ms/step - loss: 0.7532 - categorical_accuracy: 0.7144 - val_loss: 0.7469 - val_categorical_accuracy: 0.7136
Epoch 3/100
175/175 [==============================] - 51s 293ms/step - loss: 0.6640 - categorical_accuracy: 0.7537 - val_loss: 0.7211 - val_categorical_accuracy: 0.7377
Epoch 4/100
175/175 [==============================] - 47s 270ms/step - loss: 0.5941 - categorical_accuracy: 0.7817 - val_loss: 0.7370 - val_categorical_accuracy: 0.7362
Epoch 5/100
175/175 [==============================] - 47s 270ms/step - loss: 0.5421 - categorical_accuracy: 0.7996 - val_loss: 0.7690 - val_categorical_accuracy: 0.7228
Epoch 6/100
175/175 [==============================] - 47s 269ms/step - loss: 0.4864 - categorical_accurac

In [0]:
model.load_weights("/tmp/weights.03-0.72.hdf5")

In [0]:
model.evaluate(test_parsed)

     22/Unknown - 6s 288ms/step - loss: 0.7014 - categorical_accuracy: 0.7406

[0.7014398385177959, 0.7405895]

### Model accuracy

In [0]:
from sklearn.metrics import classification_report
import numpy as np

# y_pred
y_pred = model.predict(test_parsed)
y_pred = np.argmax(y_pred, axis=1)
y_pred

# y_true
y_true = []  
for __, labels in test_parsed:
  y_true += list(np.argmax(labels.numpy(), axis=1))

In [0]:
print(classification_report(y_true=y_true, y_pred=y_pred, digits=3))

              precision    recall  f1-score   support

           0      0.673     0.358     0.467       668
           1      0.717     0.849     0.778      2087
           2      0.753     0.770     0.762      1489
           3      0.789     0.730     0.758      1388

    accuracy                          0.741      5632
   macro avg      0.733     0.677     0.691      5632
weighted avg      0.739     0.741     0.732      5632



In [0]:
# prediction examples with the biggest error:
text = "Odsyłają z placówki na infolinię i z powrotem - bez sensu."

def _predict(text: str):
  inputs = bert_tokenizer.encode_plus(text, return_tensors="tf")
  probs = tf.math.softmax(model(inputs)[0]).numpy()[0, :]
  return probs

probs = _predict(text)
probs
idx = np.argmax(probs)
idx

print(f"{bert_tokenizer.tokenize(text)}: {enc.classes_[idx]}, p={probs[idx]}")

['Od', '##sy', '##ła', '##ją', 'z', 'pla', '##ców', '##ki', 'na', 'info', '##lini', '##ę', 'i', 'z', 'po', '##wr', '##ote', '##m', '-', 'bez', 'sensu', '.']: z_minus_m, p=0.7245222330093384
