<a href="https://colab.research.google.com/github/jakubglinka/google.colab/blob/master/NLP/supervised/LearningCurveBertSequenceClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Text Classification using BERT

 - using pre-trained bert model
 - learning curve

## Configure environment

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
from __future__ import absolute_import, division, print_function, unicode_literals

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
print(tf.__version__)

TensorFlow 2.x selected.
Num GPUs Available:  0
2.1.0-rc1


In [36]:
try:
  cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
  tf.config.experimental_connect_to_cluster(cluster_resolver)
  tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
  strategy = tf.distribute.experimental.TPUStrategy(cluster_resolver)
except ValueError as error:
  print(error)
  print("No TPU available. Switching to single device strategy.")
  strategy = tf.distribute.OneDeviceStrategy(device="/gpu")

INFO:tensorflow:Initializing the TPU system: 10.111.174.138:8470


INFO:tensorflow:Initializing the TPU system: 10.111.174.138:8470


INFO:tensorflow:Clearing out eager caches


INFO:tensorflow:Clearing out eager caches


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Found TPU system:


INFO:tensorflow:Found TPU system:


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


In [4]:
!pip install transformers
!pip install git+https://jbglin:botrx56jtlp6p2cbsthvt3bkslgeo3pzc5c7iuu4irxscjmmc6xa@dev.azure.com/eyDataScienceTeam/_git/nlp-ey-assets@develop

  Cloning https://jbglin:****@dev.azure.com/eyDataScienceTeam/_git/nlp-ey-assets (to revision develop) to /tmp/pip-req-build-doheuzft
  Running command git clone -q 'https://jbglin:****@dev.azure.com/eyDataScienceTeam/_git/nlp-ey-assets' /tmp/pip-req-build-doheuzft
  Running command git checkout -b develop --track origin/develop
  Switched to a new branch 'develop'
  Branch 'develop' set up to track remote branch 'develop' from 'origin'.
  Created wheel for nlp-ey-assets: filename=nlp_ey_assets-0.1.dev0-cp36-none-any.whl size=87765 sha256=fae53bf390a92c06334585bd6e3a863eb8a78d01402add053b3809035217e61e
  Stored in directory: /tmp/pip-ephem-wheel-cache-69gpx5oz/wheels/82/e1/b0/516034573f2c111d58a616e4e64b46cd8d80f52f98f07a64bb
Successfully built nlp-ey-assets


## Data Preparation

### PolEmo data

In [0]:
import pandas as pd
import pathlib
import re
import tqdm
POLEMO_PATH = "./drive/My Drive/sentiment/"
from typing import List
import numpy as np

In [6]:
# read PolEmo data:
def read_polemo_data(path) -> pd.DataFrame:
  res = []
  with path.open("r") as f:
    for line in f:
      rec = line.strip("\n").split("__label__")
      rec[0] = rec[0].strip()
      res.append(rec)

  return pd.DataFrame(res, columns=["text", "label"])

df_train = read_polemo_data(pathlib.Path(POLEMO_PATH) / "all.sentence.train.txt")
print(f"Read {df_train.shape[0]} train examples.")

df_dev = read_polemo_data(pathlib.Path(POLEMO_PATH) / "all.sentence.dev.txt")
print(f"Read {df_dev.shape[0]} dev examples.")

df_test = read_polemo_data(pathlib.Path(POLEMO_PATH) / "all.sentence.test.txt")
print(f"Read {df_test.shape[0]} test examples.")

Read 45974 train examples.
Read 5747 dev examples.
Read 5745 test examples.


In [7]:
df_train.iloc[5745, :]

text     Niestety mam podobne odczucia jak poprzedniczka .
label                                            z_minus_m
Name: 5745, dtype: object

In [0]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder().fit(df_train.label.values)

# add encoded labels:
df_train["label_enc"] = enc.transform(df_train["label"])
df_dev["label_enc"] = enc.transform(df_dev["label"])
df_test["label_enc"] = enc.transform(df_test["label"])

## Pre-Trained BERT
 - bert-base-multilingual-cased

### Prepare BertTokenizer

In [9]:
from transformers import BertTokenizer, TFBertForSequenceClassification

# create new instance of BertTokenizer
bert_tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
print(bert_tokenizer.tokenize("Ala ma kota!"))

# encode plus:
print(bert_tokenizer.encode_plus("Ala ma kota!", max_length=10, pad_to_max_length=True))

# check for number of tokens distribution
df_train["n_tokens"] = df_train.text.apply(lambda x: len(bert_tokenizer.tokenize(x)))
np.quantile(df_train.n_tokens, q=[.9, .99, .999])

['Ala', 'ma', 'kota', '!']
{'input_ids': [101, 56500, 10824, 16469, 106, 102, 0, 0, 0, 0], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 0, 0, 0, 0]}


array([ 59.   , 122.   , 243.027])

### TFRecords

#### Prepare single Example

In [10]:
bert_tokenizer.tokenize("Ala ma kota!")

['Ala', 'ma', 'kota', '!']

In [0]:
from typing import Dict
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# prepare data:
def _prepare_single_example(x: str, max_seq_len: int = None, label: int = 0) -> Dict:
  
  inputs = bert_tokenizer.encode_plus(x, max_length=max_seq_len, pad_to_max_length=False, return_tensors="tf")
  inputs["attention_mask"] = tf.squeeze(inputs["attention_mask"], axis=0)
  inputs["input_ids"] = tf.squeeze(inputs["input_ids"], axis=0)
  inputs["token_type_ids"] = tf.squeeze(inputs["token_type_ids"], axis=0)
  
  inputs["label"] = tf.convert_to_tensor(label)
  inputs["raw_text"] = tf.convert_to_tensor(x)

  return inputs

# serialize:
def _serialize_example(example):
  
  # attention mask
  example["attention_mask"] = tf.io.serialize_tensor(example["attention_mask"]).numpy()
  example["attention_mask"] = tf.train.Feature(bytes_list = tf.train.BytesList(value=[example["attention_mask"]]))
  
  # input ids
  example["input_ids"] = tf.io.serialize_tensor(example["input_ids"]).numpy()
  example["input_ids"] = tf.train.Feature(bytes_list = tf.train.BytesList(value=[example["input_ids"]]))

  # token type ids
  example["token_type_ids"] = tf.io.serialize_tensor(example["token_type_ids"]).numpy()
  example["token_type_ids"] = tf.train.Feature(bytes_list = tf.train.BytesList(value=[example["token_type_ids"]]))

  example["raw_text"] = tf.train.Feature(bytes_list = tf.train.BytesList(value=[example["raw_text"].numpy()]))
  example["label"] = tf.train.Feature(int64_list = tf.train.Int64List(value=[example["label"].numpy()]))

  ex = tf.train.Example(features=tf.train.Features(feature=example))
  return ex.SerializeToString()  

# example = _prepare_single_example("Ala ma kota!", 64, 1)
# example
# tf.train.Example.FromString(_serialize_example(example))

#### Prepare TFRecords

In [12]:
!rm ./train.TFRecord ./dev.TFRecord ./test.TFRecord

rm: cannot remove './train.TFRecord': No such file or directory
rm: cannot remove './dev.TFRecord': No such file or directory
rm: cannot remove './test.TFRecord': No such file or directory


In [13]:
np.random.seed(1234)
df_train["chunk"] = np.random.choice(range(int(df_train.shape[0]/1000)), size=df_train.shape[0])
df_train["chunk"].describe()

count    45974.000000
mean        21.921173
std         12.999854
min          0.000000
25%         11.000000
50%         22.000000
75%         33.000000
max         44.000000
Name: chunk, dtype: float64

In [14]:
# Write the `tf.Example` observations to the file.

for chunk in tqdm.tqdm(range(int(df_train.shape[0]/1000))):
  with tf.io.TFRecordWriter(f"./train_chunk_{chunk}.TFRecord") as writer:
    rows = df_train[df_train.chunk==chunk].iterrows()
    for __, row in rows:
      example = _prepare_single_example(row.text, None, row.label_enc)
      writer.write(_serialize_example(example))

with tf.io.TFRecordWriter("./dev.TFRecord") as writer:
  for __, row in tqdm.tqdm(df_dev.iterrows()):
    example = _prepare_single_example(row.text, None, row.label_enc)
    writer.write(_serialize_example(example))

with tf.io.TFRecordWriter("./test.TFRecord") as writer:
  for __, row in tqdm.tqdm(df_test.iterrows()):
    example = _prepare_single_example(row.text, None, row.label_enc)
    writer.write(_serialize_example(example))


100%|██████████| 45/45 [06:13<00:00,  8.31s/it]
5747it [00:54, 105.66it/s]
5745it [00:52, 109.51it/s]


In [15]:
!ls -la -h | grep TF

-rw-r--r-- 1 root root 3.8M Jan  7 20:23 dev.TFRecord
-rw-r--r-- 1 root root 3.8M Jan  7 20:24 test.TFRecord
-rw-r--r-- 1 root root 693K Jan  7 20:16 train_chunk_0.TFRecord
-rw-r--r-- 1 root root 663K Jan  7 20:18 train_chunk_10.TFRecord
-rw-r--r-- 1 root root 688K Jan  7 20:18 train_chunk_11.TFRecord
-rw-r--r-- 1 root root 668K Jan  7 20:18 train_chunk_12.TFRecord
-rw-r--r-- 1 root root 681K Jan  7 20:18 train_chunk_13.TFRecord
-rw-r--r-- 1 root root 698K Jan  7 20:18 train_chunk_14.TFRecord
-rw-r--r-- 1 root root 639K Jan  7 20:19 train_chunk_15.TFRecord
-rw-r--r-- 1 root root 716K Jan  7 20:19 train_chunk_16.TFRecord
-rw-r--r-- 1 root root 650K Jan  7 20:19 train_chunk_17.TFRecord
-rw-r--r-- 1 root root 670K Jan  7 20:19 train_chunk_18.TFRecord
-rw-r--r-- 1 root root 658K Jan  7 20:19 train_chunk_19.TFRecord
-rw-r--r-- 1 root root 696K Jan  7 20:17 train_chunk_1.TFRecord
-rw-r--r-- 1 root root 705K Jan  7 20:19 train_chunk_20.TFRecord
-rw-r--r-- 1 root root 686K Jan  7 20:19 train_c

#### Copy to GC Bucket

In [16]:
from google.colab import auth
auth.authenticate_user()

# https://cloud.google.com/resource-manager/docs/creating-managing-projects
project_id = 'southern-shard-211411'
!gcloud config set project {project_id}

Updated property [core/project].


In [20]:
# Upload the files to a given Google Cloud Storage bucket.
!gsutil -m cp ./train*.TFRecord gs://tf_experiments_records/PolEmo/bert/
!gsutil cp ./dev.TFRecord gs://tf_experiments_records/PolEmo/bert/dev.TFRecord
!gsutil cp ./test.TFRecord gs://tf_experiments_records/PolEmo/bert/test.TFRecord

Copying file://./train_chunk_0.TFRecord [Content-Type=application/octet-stream]...
Copying file://./train_chunk_10.TFRecord [Content-Type=application/octet-stream]...
Copying file://./train_chunk_18.TFRecord [Content-Type=application/octet-stream]...
Copying file://./train_chunk_15.TFRecord [Content-Type=application/octet-stream]...
Copying file://./train_chunk_16.TFRecord [Content-Type=application/octet-stream]...
Copying file://./train_chunk_17.TFRecord [Content-Type=application/octet-stream]...
Copying file://./train_chunk_14.TFRecord [Content-Type=application/octet-stream]...
Copying file://./train_chunk_13.TFRecord [Content-Type=application/octet-stream]...
Copying file://./train_chunk_11.TFRecord [Content-Type=application/octet-stream]...
Copying file://./train_chunk_12.TFRecord [Content-Type=application/octet-stream]...
Copying file://./train_chunk_19.TFRecord [Content-Type=application/octet-stream]...
Copying file://./train_chunk_1.TFRecord [Content-Type=application/octet-strea

### Read from GC Bucket

In [21]:
from google.colab import auth
auth.authenticate_user()

# https://cloud.google.com/resource-manager/docs/creating-managing-projects
project_id = 'southern-shard-211411'
!gcloud config set project {project_id}

Updated property [core/project].


In [23]:
# Set access for the TPU pod:
!gsutil -m acl ch -u service-495559152420@cloud-tpu.iam.gserviceaccount.com:READER gs://tf_experiments_records/PolEmo/bert/*

No changes to gs://tf_experiments_records/PolEmo/bert/dev.TFRecord
No changes to gs://tf_experiments_records/PolEmo/bert/test.TFRecord
No changes to gs://tf_experiments_records/PolEmo/bert/train_chunk_1.TFRecord
No changes to gs://tf_experiments_records/PolEmo/bert/train_chunk_0.TFRecord
No changes to gs://tf_experiments_records/PolEmo/bert/train_chunk_13.TFRecord
No changes to gs://tf_experiments_records/PolEmo/bert/train_chunk_10.TFRecord
No changes to gs://tf_experiments_records/PolEmo/bert/train_chunk_11.TFRecord
No changes to gs://tf_experiments_records/PolEmo/bert/train_chunk_14.TFRecord
No changes to gs://tf_experiments_records/PolEmo/bert/train_chunk_2.TFRecord
No changes to gs://tf_experiments_records/PolEmo/bert/train_chunk_12.TFRecord
No changes to gs://tf_experiments_records/PolEmo/bert/train_chunk_15.TFRecord
No changes to gs://tf_experiments_records/PolEmo/bert/train_chunk_17.TFRecord
No changes to gs://tf_experiments_records/PolEmo/bert/train_chunk_16.TFRecord
No changes

In [37]:
# Create a dictionary describing the features.
_feature_description = {
    'attention_mask': tf.io.FixedLenFeature([], tf.string),
    'input_ids': tf.io.FixedLenFeature([], tf.string),
    'token_type_ids': tf.io.FixedLenFeature([], tf.string),
    'label': tf.io.FixedLenFeature([], tf.int64)
}

def _parse_data(example_proto, max_seq_len: int = 128):
  # Parse the input tf.Example proto using the dictionary above.
  rec = tf.io.parse_single_example(example_proto, _feature_description)
  
  # attention_mask:
  rec["attention_mask"] = tf.io.parse_tensor(rec["attention_mask"], out_type=tf.int32)
  rec["attention_mask"] = rec["attention_mask"][:max_seq_len]
  n_tokens = tf.shape(rec["attention_mask"])[0]
  padding = max_seq_len - n_tokens
  rec["attention_mask"] = tf.pad(rec["attention_mask"], paddings=[[0, padding]])

  # input_ids:
  rec["input_ids"] = tf.io.parse_tensor(rec["input_ids"], out_type=tf.int32)
  rec["input_ids"] = rec["input_ids"][:max_seq_len]
  rec["input_ids"] = tf.pad(rec["input_ids"], paddings=[[0, padding]])
  
  # token_type_ids
  rec["token_type_ids"] = tf.io.parse_tensor(rec["token_type_ids"], out_type=tf.int32)
  rec["token_type_ids"] = rec["token_type_ids"][:max_seq_len]
  rec["token_type_ids"] = tf.pad(rec["token_type_ids"], paddings=[[0, padding]])
 
  # shape bug?
  # rec["text/embedding"] = tf.reshape(rec["text/embedding"], [64, 256])
  rec["attention_mask"] = tf.reshape(rec["attention_mask"], [max_seq_len, ])
  rec["input_ids"] = tf.reshape(rec["input_ids"], [max_seq_len, ])
  rec["token_type_ids"] = tf.reshape(rec["token_type_ids"], [max_seq_len, ])
 
  labels = tf.one_hot(rec["label"], depth=4)
  inputs = rec
  inputs.pop("label")

  return inputs, labels

train_raw = tf.data.TFRecordDataset("gs://tf_experiments_records/PolEmo/bert/train_chunk_0.TFRecord", num_parallel_reads=4)
example_proto = next(iter(train_raw))
_parse_data(example_proto, max_seq_len=12)

({'attention_mask': <tf.Tensor: shape=(12,), dtype=int32, numpy=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0], dtype=int32)>,
  'input_ids': <tf.Tensor: shape=(12,), dtype=int32, numpy=
  array([  101,   348, 11335, 54276,   118, 10183, 10113, 74552,   119,
           102,     0,     0], dtype=int32)>,
  'token_type_ids': <tf.Tensor: shape=(12,), dtype=int32, numpy=array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)>},
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 0., 0.], dtype=float32)>)

In [51]:
BATCH_SIZE = 8*64
TRAINING_SIZE = 40000
STEPS_PER_EPOCH = int(np.floor(TRAINING_SIZE / BATCH_SIZE)) + 1
VALIDATION_STEPS = int(np.floor(5700 / BATCH_SIZE))

cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_cluster(cluster_resolver)
tf.tpu.experimental.initialize_tpu_system(cluster_resolver)
strategy = tf.distribute.experimental.TPUStrategy(cluster_resolver)

print(f"STEPS_PER_EPOCH: {STEPS_PER_EPOCH}")
print(f"VALIDATION_STEPS: {VALIDATION_STEPS}")

filenames = [f"gs://tf_experiments_records/PolEmo/bert/train_chunk_{chunk}.TFRecord" for chunk in range(40)]

train_raw = tf.data.TFRecordDataset(filenames, num_parallel_reads=1)
train_parsed = train_raw.map(_parse_data).batch(BATCH_SIZE, drop_remainder=True).repeat(200)
train_parsed = train_parsed.prefetch(-1)

inputs, labels = next(iter(train_parsed))

dev_raw = tf.data.TFRecordDataset("gs://tf_experiments_records/PolEmo/bert/dev.TFRecord", num_parallel_reads=1)
dev_parsed = dev_raw.map(_parse_data).batch(BATCH_SIZE, drop_remainder=True)
dev_parsed = dev_parsed.prefetch(-1)

test_raw = tf.data.TFRecordDataset("gs://tf_experiments_records/PolEmo/bert/test.TFRecord", num_parallel_reads=1)
test_parsed = test_raw.map(_parse_data).batch(BATCH_SIZE, drop_remainder=True)
test_parsed = test_parsed.prefetch(-1)

inputs

INFO:tensorflow:Initializing the TPU system: 10.111.174.138:8470


INFO:tensorflow:Initializing the TPU system: 10.111.174.138:8470


INFO:tensorflow:Clearing out eager caches


INFO:tensorflow:Clearing out eager caches


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Found TPU system:


INFO:tensorflow:Found TPU system:


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


STEPS_PER_EPOCH: 79
VALIDATION_STEPS: 11


{'attention_mask': <tf.Tensor: shape=(512, 128), dtype=int32, numpy=
 array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>,
 'input_ids': <tf.Tensor: shape=(512, 128), dtype=int32, numpy=
 array([[  101,   348, 11335, ...,     0,     0,     0],
        [  101, 10685, 10563, ...,     0,     0,     0],
        [  101, 14925, 21978, ...,     0,     0,     0],
        ...,
        [  101, 52742, 67935, ...,     0,     0,     0],
        [  101, 82376, 12414, ...,     0,     0,     0],
        [  101, 11255, 24378, ...,     0,     0,     0]], dtype=int32)>,
 'token_type_ids': <tf.Tensor: shape=(512, 128), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ...,

### Model training

In [0]:
with strategy.scope():
  tf.random.set_seed(1234)
  model = TFBertForSequenceClassification.from_pretrained('bert-base-multilingual-cased', 
                                                          num_labels=4, 
                                                          hidden_dropout_prob=0.1, 
                                                          attention_probs_dropout_prob=0.1)

  initial_learning_rate = 1e-5
  lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate,
    decay_steps=STEPS_PER_EPOCH*10000,
    decay_rate=.99,
    staircase=True)
  
  model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr_schedule), 
                loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True), 
                metrics=[tf.keras.metrics.CategoricalAccuracy()])

In [53]:
callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=5)
model.fit(train_parsed, 
          validation_data=dev_parsed, 
          epochs=100,
          steps_per_epoch=STEPS_PER_EPOCH, 
          validation_steps=VALIDATION_STEPS,
          callbacks=[callback])

Train for 79 steps, validate for 11 steps
Epoch 1/100
79/79 [==============================] - 115s 1s/step - loss: 1.0752 - categorical_accuracy: 0.5523 - val_loss: 0.9030 - val_categorical_accuracy: 0.6456
Epoch 2/100
79/79 [==============================] - 39s 490ms/step - loss: 0.8245 - categorical_accuracy: 0.6877 - val_loss: 0.8133 - val_categorical_accuracy: 0.6873
Epoch 3/100
79/79 [==============================] - 39s 491ms/step - loss: 0.7256 - categorical_accuracy: 0.7281 - val_loss: 0.7813 - val_categorical_accuracy: 0.7051
Epoch 4/100
79/79 [==============================] - 39s 493ms/step - loss: 0.6623 - categorical_accuracy: 0.7552 - val_loss: 0.7752 - val_categorical_accuracy: 0.7152
Epoch 5/100
79/79 [==============================] - 39s 493ms/step - loss: 0.6100 - categorical_accuracy: 0.7752 - val_loss: 0.7671 - val_categorical_accuracy: 0.7211
Epoch 6/100
79/79 [==============================] - 39s 492ms/step - loss: 0.5642 - categorical_accuracy: 0.7940 - val_

In [0]:
# 1000: 58.20
# 10000: 67.35
# 20000: 70.33
# 40000: 73.08